apiVersion: batch/v1
kind: Job
metadata:
  name: cp-tls-usr-secret
  namespace: ventress6
spec:
  template:
    metadata:
      name: cp-tls-usr-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret ventress6-tls-user -n ventress6 | grep found)\" ]; \
          then kubectl get secret ventress6-tls-user -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"ventress6\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences,  .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n ventress6 -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
